export { ReactComponent as Droplet } from './droplet.svg'
export { ReactComponent as Wind } from './wind.svg'
export { ReactComponent as Uv } from './uv.svg'
export { ReactComponent as Location } from './my-location.svg'
export { ReactComponent as IconSearch } from './search.svg'
export { ReactComponent as IconHome } from './home.svg'
export { ReactComponent as IconEmpty } from './empty.svg'
