export { ReactComponent as IconDroplet } from './droplet.svg'
export { ReactComponent as IconWind } from './wind.svg'
export { ReactComponent as IconUv } from './uv.svg'
export { ReactComponent as IconLocation } from './my-location.svg'
export { ReactComponent as IconSearch } from './search.svg'
export { ReactComponent as IconHome } from './home.svg'
export { ReactComponent as IconEmpty } from './empty.svg'
